### ISSUE TITLE
Cannot find namespace Proteomics.Utilities

### ISSUE THREAD

**Issue by wuwo007** [olivierlizotte/Iso-PeptidAce#2]
When I am building this project, I encounter some problems about the reference.  The reference DLL must be agree with the project in processor architecture (X86, X64) and .Net framework. Could you share a suit of usable reference DLLs? Thanks!

**Comment by courcelm** [comment]
The code for Proteomics.Utilities is here:
https://github.com/olivierlizotte/Proteomics.Utilities

**Comment by wuwo007** [comment]
Thanks for your help. The namespace of Proteomics.Utilities is OK.
However, I encounter one problem about PeptidAce.Library.dll: The function Ace.Start() is used in the "StatsMaker.cs" like this "Result SpikedResult = Ace.Start(options, samplesSynth, false, false);" .
But the statement of  Ace.Start()  in "PeptidAce.Ace.cs" is "public static Result Start(DBOptions dbOptions, string fasta, Samples project, bool loadMS1 = true, bool filterMS2 = true, Queries queries = null);".
Please note that the second parameter in the statement is string, but the type of samplesSynth is Samples. Could you help me to solve this problem?

**Comment by courcelm** [comment]
Can you add the fasta string?

**Comment by wuwo007** [comment]
I have changed your code to  run it. But I don't know if the project function is still OK.
Thanks for your help.
